import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {db} from '../services/database'
import {DB} from '../services/databaseClass'
import { useEffect } from 'react'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
  const router = useRouter()
  

  // useEffect(() => {
  //   console.log(props)
  // }, [props])
  
  return (
    <>
      <Head>
        <title>Horários - IFRO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/ifro.png"
            alt="Logo Ifro"
            width={250}
            height={220}
          />
        </div>
        <h1 className={inter.className}>Sistema de Relatório de Horários</h1>

        <div className={styles.grid}>
          <a onClick={() => router.push('/disciplinas')} className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>Disciplinas <span>-&gt;</span></h2>
            <p className={inter.className}>Visualise e cadastre novas disciplinas.</p>
          </a>
          <a onClick={() => router.push('/docentes')} className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>Docentes <span>-&gt;</span></h2>
            <p className={inter.className}>Visualise e cadastre o corpo docente.</p>
          </a>
          <a onClick={() => router.push('/ambientes')} className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>Ambientes <span>-&gt;</span></h2>
            <p className={inter.className}>Visualise e cadastre salas, laboratórios e auditórios.</p>
          </a>
          <a onClick={() => router.push('/horarios')} className={styles.card} rel="noopener noreferrer">
            <h2 className={inter.className}>Horários <span>-&gt;</span></h2>
            <p className={inter.className}>Visualise e cadastre os relatórios de horários das turmas.</p>
          </a>
        
        </div>
      </main>
    </>
  )
}

// export async function getServerSideProps(context: any) {
//   const disciplinas = await DB.getDisciplinas()
//   const disciplinasClass = await DB.getDisciplinas()
//   return {
//     props: {disciplinas}, // will be passed to the page component as props
//   }
// }